ruby '2.5.0'
source 'https://rubygems.org'

gem 'dotenv'
gem 'rake'
gem 'sequel'
gem 'sqlite3'
gem 'json'
gem 'curb'
gem 'google-cloud-language'
gem 'google-cloud-translate'
# gem 'sinatra'
# gem 'nokogiri'
# gem 'foreman'
# gem 'puma'
